# Blog Theme
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: simondotm


description: > # this means to ignore newlines until "baseurl:"
  Retro &| tech mutterings.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://simondotm.github.io/" # the base hostname & protocol for your site

#These settings might be able to go?
author: Simon Morris
twitter_username: podvilla
github_username:  simondotm
company_name: 

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

